version: '3.7'

networks:
  default:
    name: financial_network

services:
  postgres:
    image: postgres:15.2-alpine3.17
    container_name: financial-postgres.docker.net
    shm_size: 1gb
    command: |-
      postgres
    environment:
      - POSTGRES_PASSWORD=test
      - PGDATA=/var/lib/postgresql/data/pg_data
    ports:
      - 5432:5432
    volumes:
      - ${DATA_DIR}/postgres/data:/var/lib/postgresql/data
      - ${DATA_DIR}/postgres/backup:/var/lib/postgresql/backup
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        aliases:
          - financial-postgres
  pgadmin:
    image: dpage/pgadmin4:6.20
    container_name: financial-pgadmin.docker.net
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@mail.com
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
      - 30002:80
    expose:
      - 30002
    volumes:
      - ${DATA_DIR}/pgadmin/data:/var/lib/pgadmin
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        aliases:
          - financial-pgadmin
